services:
  - type: web
    name: school-erp-backend
    runtime: docker
    rootDir: cn_backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: APP_NAME
        value: Greenwood Academy ERP
      - key: APP_VERSION
        value: 1.0.0
      - key: DEBUG
        value: "false"
      - key: ALLOWED_ORIGINS
        sync: false
